### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by mgutierrezp** [gehelem/als#188]
Hi,

I'm running als 0.7 dev 1533ab0. When opening any settings with  "Change" button, the app crashes when trying to open the dialog box (cored  dumped).

Running on linux mint 20

m

**Comment by gehelem** [comment]
Hi, thank you for your report

i'm afraid @deufrai is really busy at the moment, and he won't be able to help us
did you try other releases, at least the latest ?

https://als-app.org/nightlies/latest/

G.

**Comment by mgutierrezp** [comment]
hi,

yes, I tried the latest version and the problem persisted. I managed to execute from the source/git version and that problem is solved. However, it crashed again while stacking

m

**Comment by gehelem** [comment]
This bug is known and we have a workaround, could you try it ?



Find file ".als.cfg" in your home folder (hidden file...), or create it if it doesnt exists.

And update its content with this, of course adapt username and folder names :

[main]

scan_folder_path = /home/yourusername/Desktop/als_scan

work_folder_path = /home/yourusername/Desktop/als_work

window_geometry = 0,52,1920,1000

log_level = DEBUG

full_screen = 0

www_dedicated_folder = 0

web_folder_path = /home/yourusername/Desktop/als_work

alignment_minimum_match_count = 25

use_master_dark = 1

use_hot_pixel_remover = 1

save_on_stop = 0

web_refresh_period = 5

night_mode = 0

master_dark_file_path = /home/yourusername/Desktop/masterDark.fit

lang = en

**Comment by mgutierrezp** [comment]
Thanks for the reply.

Yes, I was aware of that file; and that's the workaround I thought. The problem is that I may need to change the dark very frequently, and that's a bit cumbersome.

In any case, good to know that the bug is known. 

Just for my knowledge; is this software still maintained. It's a great piece of software with many useful tools (the web service is really useful) and would be a pity it comes unmaintained :(

Thanks for the effort to all the team.

m

**Comment by deufrai** [comment]
Hi

This is a duplicate of #156 
It will eventually be fixed, given enough thoughts & sweat. Bare with us :)
