### ISSUE TITLE
Devise a versionning / branching / release scheme

### ISSUE THREAD

**Issue by deufrai** [gehelem/als#26]
We need to 
- specify our dev workflow 
- specify what versioning scheme we'll use, and start to use it
- specify how project is released

**Comment by gnthibault** [comment]
Thank you @deufrai 
* Dev workflow 
I do not know exactly what you mean by that. But when we'll have a more proper mvc structure, it would be great to setup some tests + testing bot, at least for the backend.

* versioning, I just know about a few sets of generic rules for semantic versionning: https://semver.org/

* Not much experience with actual releasing for that type of software. Just deciding over a set of feature for next release, and issue tag + release whenever feature are implemented+tested

Main question for the future developement, (at least for me) would be: how about going for a live version for planetary imaging ?
I would start with a simple version that get image stream directly from pyindi client instead of reading from disk.
To do so we should also try to implement a notion of pipeline with different brick like:
-image quality metric (given stack of previous images)
-morphing
-optical flow estimation
-registering
-stacking
-denoising
-...

**Comment by deufrai** [comment]
+1000 on structure and tests & semver

**Comment by deufrai** [comment]
Let's just keep doing ALZ style
