### ISSUE TITLE
new feature : Region of Interest

### ISSUE THREAD

**Issue by deufrai** [gehelem/als#38]
Allow user to define a rectangular region inside the image and crop display according to that region

**Comment by gnthibault** [comment]
That would be an absolutely awesome feature!

**Comment by deufrai** [comment]
On another hand, it would be also great to let user dynamically pan and zoom on result image. 

But ROI has the advantage of allowing us to do post processing adjustments on a smaller data set, gifting us with a speed gain...

What do you guys think ?

**Comment by gnthibault** [comment]
That is actually a good question. For now I do have enough power to compute the resulting image in a reasonable time (for planetary imaging, this might be different).
So for my dslr setup, just giving the ability to zoom here and there on the image would be enough.
I think we do not need the exported image (the jpeg to be served by webserver) to be cropped, because any attendant should be able to zoom by himself.

Anyway, for now at least I would find it ok to have a ROI concept defined only for the GUI, and keep manipulating the image as a whole in the rest o the software.

For planetary imaging, again, the deal might be different, in this case I would find it ok to have a global ROI and only do processing on this roi (might even be a planet-centered ROI).

**Comment by deufrai** [comment]
then, as I'm quite sure Qt offers a scrollable & zoomable view we can put our image into, 
that would be a good start. And if we ear people use ALS on tiny / nomad systems, we'll see if processing speed becomes an issue. In that case, ROI can be added upstream. Where exactly in the pipeline ( preprocessing, stacking, processing) will be an interresting issue to discuss

**Comment by deufrai** [comment]
closing

Done with 7891981 and 0b73f9f
